openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    Sample Input Validation APP
  version: 1.0.11
servers:
  - url: https://localhost:8080
tags:
  - name: Strings
    description: String 
paths:
  /concatStrings:
    get:
      tags:
        - Strings
      summary: Consent Strings
      parameters: 
        - name: firstString
          in: query
          schema: 
            type: string
            minLength: 1
            maxLength: 10
            pattern: "^[a-z]$"
          required: true
        - name: secondString
          in: query
          schema: 
            type: string
            minLength: 1
            maxLength: 10
          required: true
      responses:
        '200':
          description: Successful operation
  /createUser:
    post:
      tags:
        - Strings
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: OK
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          example: "Tan See Ling Jr."
          pattern: "/^[a-z ,.'-]+$/i"
        age: 
          type: integer
          format: int32
          example: 12
          minimum: 0
        birthday:
          type: string
          format: date
        identification:
          oneOf:
            - $ref: '#/components/schemas/hkid'
            - $ref: '#/components/schemas/passport'
      required:
        - name
        - age
        - birthday
        - identification
    hkid:
      type: object
      properties:
        type:
          type: string
          enum: ['hkid']
        value:
          type: string
          pattern: ^[A-Z]{1,2}[0-9]{6}\([0-9A]\)$
          example: N123456(A)
      required:
        - type
        - value
    passport:
      type: object
      properties:
        type:
          type: string
          enum: ['passport']
        value:
          type: string
          pattern: ^[A-Z]{1,2}[0-9]{6}[0-9A-F]{1}
          example: AS123123A
      required:
        - type
        - value
        
          
        
          
        
        
      

